# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

RUST_MIN_VER="1.85.0"

inherit cargo

DESCRIPTION="Bash compatibility layer for fish shell"
HOMEPAGE="https://github.com/ZStud/reef"
SRC_URI="https://github.com/ZStud/reef/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64"
